name: cap_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - pip


  # Main data handling
  - pyproj==3.4.0
  - iris
  - xarray
  - pandas
  - geopandas
  - "shapely<2"
  - cftime=1.2
  - cf-units==2.1.5

  # Plotting
  - holoviews==1.14.9
  - hvplot
  - panel

  # Dev
  - pytest
  - flake8
  - boto3-stubs-essential
  - pip:
    - tox<4.0.0 # The conda package didn't install correctly, but using the pip package did
    - moto>=3.0.1
    - https://github.com/MetOffice/edr_server/archive/refs/heads/main.zip#egg=edr_server
    - https://github.com/ADAQ-AQI/cap-sample-data/archive/main.zip#egg=cap_sample_data
    - -e .  # Install the source code in development mode. The argument is the path to the folder containing the setup.cfg
