name: cap_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - pip

  - boto3
  # Main data handling
  - iris
  - xarray
  - pandas
  - geopandas
  - openpyxl

  # Plotting
  - hvplot
  - panel
  - folium

  # Dev
  - pytest
  - flake8
  - boto3-stubs-essential
  - pip:
    - moto>=2.2.16
