name: cap_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - pip


  # Main data handling
  - iris
  - xarray
  - pandas
  - geopandas

  # Plotting
  - hvplot
  - panel

  # Dev
  - pytest
  - flake8
  - boto3-stubs-essential
  - pip:
    - tox<4.0.0 # The conda package didn't install correctly, but using the pip package did
    - moto>=3.0.1
    - -e .  # Install the source code in development mode. The argument is the path to the folder containing the setup.cfg
    - https://github.com/ADAQ-AQI/cap-sample-data/archive/make_package.zip
